### ISSUE TITLE
Week 1: To do

### ISSUE THREAD

**Issue by mpatricia01** [anyone-can-cook/rclass2#1]
cc: @ozanj , @cyouh95 

- [x] Edit lecture
- [x] Edit problem set
- [x] Email class with zoom link and software installation
- [x] Syllabus
- [x] Class website
- [ ] Add instructions for creating a repo and submitting/pushing the problem sets to their repo?
- [x] Dropbox folders for problem sets
- [x] Create class announcement team
- [x] Create class repo
- [x] Post lecture, problem set, & assigned readings on the class website

These are the things that came to mind. Feel free to edit and add as you see fit. Below create a comment and assign yourself 
and check the boxes that are completed.

**Comment by mpatricia01** [comment]
Patricia's to do

- [x] Edit lecture
- [x] Problem set (working on rubric)
- [x] Create class zoom link
- [x] Email class with zoom link and important information
- [x] Syllabus
- [x] Dropbox folder for problem sets
- [x] Invite students to class announcement team & repo

**Comment by cyouh95** [comment]
Crystal's to do

- [ ] Post lecture, problem set, & assigned readings on the class website
- [ ] Add instructions for creating a repo and submitting/pushing the problem sets to their repo

**Comment by mpatricia01** [comment]
Just looked at the syllabus. It looks good. 

We need to add our office hours and I think the section "Course structure" needs some rewording (Ozan).

**Comment by ozanj** [comment]
Thanks patricia,

 

Can you remind me on Thursday afternoon to do this stuff. Thx!

 

Ozan Jaquette

Associate Professor

he/him/his

Higher Education and Organizational Change

UCLA Graduate School of Education & Information Studies

Moore Hall 3038

 <mailto:ozanj@ucla.edu> ozanj@ucla.edu

310-206-3030

 

 <https://emraresearch.org/> https://emraresearch.org/ 

 

“Don’t tell me what you value. Show me your budget and I’ll tell you what you value.” – Joe Biden

**Comment by ozanj** [comment]
cc: @cyouh95 @mpatricia01 

FYI - I just revised the course structure section of syllabus and pushed
