### ISSUE TITLE
programming lecture, conditional execution and functions

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass2#12]
CC: @mpatricia01 

@cyouh95 - 

Some small things on lecture

for conditional execution section

- at very very top of section, say what is "conditional execution" and why is it important?
- before section sub-section on "if statement conditions" there should be a sub-section on "conditions"; [I ALREADY STARTED ADDING THIS]

for functions section

- throughout the print_hello() function example [5.2.2] and the z_score() function example [5.2.3], there are parts where you identify function name, function arguments, and function body. make sure to always add what the function returns [call it function output/function return or something]. this would give like the object type/length whatever that is returned when you call the function
- when you first talk about what a function returns [in 5.1], say that a good way to check on what a function returns is to wrap the function call in `str()` (e.g., `my_function(x = object) %>% str()`
  - later on in lecture I added some lines of code showing this within the examples 

oh, and LECTURE IS FABULOUS!!!

**Comment by cyouh95** [comment]
Done!
