### ISSUE TITLE
ps9 embarrassing questions

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass2#14]
@cyouh95 @mpatricia01 

a couple embarrassing questions that came up while I was doing ps9, part III

Why do these two strings print differently when using `print()`

```
> print('\'')
[1] "'"
> print("\"")
[1] "\""
```

3.2 why do both these solutions work?
```
string_with_quotes <- 'this is my string with quotes. it has single quote \' and it has a double quote \" in it' 

str_view_all(string = string_with_quotes, pattern = '\"', match = NA)
str_view_all(string = string_with_quotes, pattern = '\\"', match = NA)
```

3.3, why do both these solutions work?
```
string_with_spchars <- 'this is my string with special characters. it has a tab \t and it has a newline \n in it' 

str_view_all(string = string_with_spchars, pattern = '\\t', match = NA)
str_view_all(string = string_with_spchars, pattern = '\t', match = NA)
```

3.4, why do both these solutions work?
```
string_with_spchars <- 'this is my string with special characters. it has a tab \t and it has a newline \n in it' 

str_view_all(string = string_with_spchars, pattern = '\\n', match = NA)
str_view_all(string = string_with_spchars, pattern = '\n', match = NA)
```

**Comment by cyouh95** [comment]
- I believe R stores strings internally using double quotes, so even if we use single quotes to create the string, it'll show up as double quotes when we `print()`
- For 3.2, quotes don't mean anything special in regex, so we don't have to escape them (i.e., just use `"` as the regex to match the quotes), which is what your first way is doing. But I think it doesn't hurt to escape either and use `\"`, which is what your second way is doing, so both works!
    ```r
    # First way
    > writeLines('\"')
    "
    ```
    ```r
    # Second way
    > writeLines('\\"')
    \"
    ```
- For 3.3 (and 3.4), it looks like the first way is using the regex `\t` to match the tab character, while in the second way, the string `'\t'` becomes a literal tab character (`	`) that's used as the regex, which can match tab characters as well.

**Comment by ozanj** [comment]
Thank you @cyouh95 !!!!
