### ISSUE TITLE
PS1_Part 2.2 Error Downloading Data

### ISSUE THREAD

**Issue by ecedwards01** [anyone-can-cook/rclass2#16]
I'm trying to download the data file that we were provided a URL for, but I keep getting the following error message:

![Screen Shot 2022-01-11 at 12 50 21 PM](https://user-images.githubusercontent.com/91282339/149019468-644c612f-321f-4d8a-8b39-ef13e8254245.png)

Does this mean that the file doesn't actually exist or Is there something wrong with my code? 

download.file(url= 'https://github.com/anyone-can-cook/rclass2/raw/main/data/ps2_files.zip', 
              destfile = file.path(input_data_dir, 'ps2_files.zip'))

@ozanj @lizachavac @briannawright135

**Comment by lizachavac** [comment]
@ecedwards01 hi! what was your relative path for the data folder?

**Comment by ecedwards01** [comment]
@lizachavac The relative path is

./ps1_directory/data

**Comment by shanmiss6** [comment]
And the realative path is the temporary path for the document? Can relative be the same as the absolute?

**Comment by ozanj** [comment]
Hi @shanmiss6 ! 

I think of working directory "current" directory (folder) that R is looking at. but you can also think of the working directory as the "temporary" directory R is looking at

relative file-path is the path to go to from the current working directory to some particular file

it is possible for "relative" file path and "absolute" file path to be the same. but this is quite rare

absolute file path shows the path from the root directory of your computer to some file, like this is absolute file path to my "rclass2" folder 

C:\Users\ozanj\Documents\rclass2

the relative filepath would only be the same as the absolute file path if my working directory is the folder where C: is located

**Comment by ozanj** [comment]
@ecedwards01 and @shanmiss6 , I just realized that this comment was in the rclass2 github repository. 

https://github.com/anyone-can-cook/rclass2/issues

can you use this one instead for comments/questions

https://github.com/anyone-can-cook/rclass2_w22_student_issues/issues 

thx!
