### ISSUE TITLE
gitignore

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass2#2]
cc: @mpatricia01 

@cyouh95 - as you continue to revise the git_and_github.rmd lecture, can you create a section of subsection on .gitignore?

I know .gitignore was covered briefly in section 5 [git commands: observing your respository] but I think it should be discussed/introduced in more depth, with examples.

I'm not yet sure whether we would cover this section in the 2nd or the 3rd week of our three-week github unit. we can decide that later.

I know that one thing that surprised [and disappointed me] about .gitignore is that it does not support regular expressions. rather it supports ["unix fnmatch style patterns"](https://stackoverflow.com/questions/30084715/does-gitignore-support-regexp#:~:text=No%2C%20gitignore%20doesn't%20support,you%20could%20try%20using%20modules.)

so part of this .gitignore section should state what these are and how to use some of the basics.

@cyouh95 - I would also greatly appreciate it if you developed a .gitignore template that we put in the "syllabus and resources" section of the rclass2 website. this .gitignore template would explain a bunch of relevant stuff at the top in comments, like:

- what is .gitignore
- what are "unix fnmatch style patterns", some of the most useful ones, examples of how to use them
- examples [in comments] of sorts of files, filetypes, directories we would like to ignore
- should give reader a sense of how to organize a .gitignore file etc.

this will be a great resource for students and will be a great resource for us down the road, cuz I always forget this stuff!

part of this section/subsection should describe the

**Comment by cyouh95** [comment]
I added a section for `.gitignore` in the lecture appendix. For templates, should we use the templates from [here](https://github.com/github/gitignore) (e.g., [R template](https://github.com/github/gitignore/blob/master/R.gitignore))? I copied the R template and added some info on top [here](https://github.com/anyone-can-cook/rclass2/blob/d690b673531cb80498ff9d0b0d2d8ebf43a9c2f8/assets/resources/gitignore_template.txt).

**Comment by ozanj** [comment]
I like the template you created based on the standard R template. I think maybe delete lines that are less useful for students (e.g., stuff they won't encounter that much) and add some more examples of things they will encounter (e.g., if they want to ignore all files in a particular directory (like input data directory) or something.

**Comment by cyouh95** [comment]
Okay! I removed some of the lesser used lines and added a couple examples at the top in comments. Do those look okay?

**Comment by ozanj** [comment]
@cyouh95 

cc: @mpatricia01 

can you create an in-class exercise [similar to wonderful one you created last week] about .gitignore. 

we will start class on Friday w/ this exercise. we should assume no prior knowledge of .gitignore. so we will start by briefly lecturing on .gitignore from appendix of our lecture. and then introduce the exercise. something that helps students understand what it is, why it is useful, and how to use it

something that makes students get it is when you have changes that are not tracked/added/or committed and you change the .gitignore to include/exclude certain files or folders and then type "git status" then make more changes to .gitignore and type "git status"

**Comment by cyouh95** [comment]
[Here](https://gist.github.com/cyouh95/ee721afd4b13cefb02d1888d0d7a1a20)'s the link to a draft of the class activity. How does this look?

**Comment by ozanj** [comment]
Exercise looks great!

one thing to change, I think having students change .gitignore by typing `echo some_text > .gitignore` in command line adds confusion for students. can you revise directions so that student will be just opening up .gitignore as a text file within Rstudio and modifying it directly there? that seems to be more consistent w/ how people modify .gitignore files in real project work anyways. But I like keeping the `echo some_text > .gitignore` solutions just the way you have them.

**Comment by cyouh95** [comment]
Okay! Agreed - I've updated the gist.

**Comment by mpatricia01** [comment]
@cyouh95 exercise looks great!
