### ISSUE TITLE
ps8 solutions file missing

### ISSUE THREAD

**Issue by augias** [anyone-can-cook/rclass2#20]
Hey @ozanj I noticed ps8 didn't have a solutions script on [Box](https://ucla.app.box.com/folder/1535667425). All the other sets are fine. Wondering if this is on purpose, or if you might have a solution file floating around? Otherwise assign me to create it and ill have it done by week 7/8.

ps: already uploaded up to date RMD and PDF files with links to issues repo and up to date github handles to box. Should be good to go from the site

**Comment by ozanj** [comment]
Hello @augias !

sorry for confusion. the solutions for PS8 are in the folder for PS7. 

if I recall, this is because PS8 uses the directory structure created for PS7.
