### ISSUE TITLE
Git lecture 2 / ps4 update: leaving git log.

### ISSUE THREAD

**Issue by augias** [anyone-can-cook/rclass2#22]
Hola

Unsure if this is the same experience for mac or windows rstudio users. In a console, or the rstudio console window, `git log` enters a viewer state where no terminal commands are possible. I need to press `ctrl+z` to exit on linux and get back to a usable console. Like so:

![Screenshot from 2023-01-16 11-45-48](https://user-images.githubusercontent.com/19480035/212755421-3e4160a8-7e5a-4dd7-a567-81c28326781f.png)

Question 1: If its the same on mac and windows, I think it'd be useful to add a hint/reminder on ps4, part II, question 6 that you can escape from git's log using ctrl+z.

Question 2: what is the command on windows? what is the command on macintosh?

**Comment by joycehnguy** [comment]
YES this is so annoying. I noticed it before and was stressed out by it. For mac for me it's not command z, it's control z - command z does not exit out of it? 

Not sure about windows.

**Comment by augias** [comment]
control, you're right. I dont even look at these buttons, forgot cmd is on mac. Edited the original comment to say ctrl

**Comment by cyouh95** [comment]
Typing `q` (for quit) should work as well!

**Comment by augias** [comment]
> Typing `q` (for quit) should work as well!

Wow ; :woah:

This is so much easier.

**Comment by ozanj** [comment]
was about to say same thing. thank you @cyouh95 !
