### ISSUE TITLE
git merge

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass2#4]
cc @mpatricia01 

@cyouh95 - can you add a subsection on "git pull." this will be a subsection of "merging"

idea here is that git pull is git fetch followed by git merge. give a couple of examples (e.g., showing git pull vs. git fetch followed by git merge). we won't get to this until week 3 of the unit, but writing this now because it is on my mind. showing students this and giving them some practice will help them have deeper understanding of core concepts around git.

also, can you add a bit more on git fetch and put it somewhere in the topics that we will cover in week 2? indluding, why/when would we want to git fetch rather than go immediately to git pull

**Comment by cyouh95** [comment]
Just added a small part under section 6.3 (`HEAD` and `refs/`) talking about `git fetch` and when it might be useful. I'll add the stuff for week 3 in the next couple days.

**Comment by ozanj** [comment]
thx!

**Comment by ozanj** [comment]
@cyouh95 

cc: @mpatricia01 

create subsection of merging called git pull that would go after 9.1 git merge and before 9.2 merge conflicts. explain it simply and provide an example. 

include a conceptual figure in the section

**Comment by cyouh95** [comment]
This is added!

**Comment by ozanj** [comment]
Thx!
