### ISSUE TITLE
2/5/2021 synchronous class, revisions to lecture

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass2#6]
@cyouh95 

cc: @mpatricia01 

for synchronous lecture this upcoming week, we will do branching and merging.

I want to skip section on "pull requests" this  year.

in revising sections on branching and merging:

- there are already some conceptual figures there. but if you see any opportunity where adding another conceptual figure could help student understanding, then do so. as we teach this unit again, I am reminded that the real understanding comes from conceptual understanding of the flow of git operations. so I want students to understand concepts/definitions and then have mental figures in their head of this flow. otherwise, they are just pasting in code but they don't know why. so I want to stress conceptual figures in lecture. that said, if there just isn't any need to add more, then so be it.

**Comment by cyouh95** [comment]
I added an image under `git checkout` section for switching branches (and also one for last week's section on `git revert` vs. `git reset`)
