### ISSUE TITLE
branch and remotes

### ISSUE THREAD

**Issue by ozanj** [anyone-can-cook/rclass2#8]
cc: @mpatricia01 

@cyouh95 - in the Branching >> git branch section:

- in the example where you use "git branch -a" to show local and remote branches, give a bit more intuition/guidance on how to interpret the output associated with the remote branches 

e.g., what does each part of the following output mean:

`##   remotes/origin/HEAD -> origin/master`

at end of the git branch section, add a short subsection on connecting your local branch to the remote repository.

- provide some intuition about why they might want to connect local branch to remote
- provide a conceptual figure that shows flow of what is going on here
- explain that this is just an application of stuff students have previously done (when they initialize a repo on local machine and then connect the repo to remote
- make sure all terms defined
- provide an example

**Comment by cyouh95** [comment]
Updated `git branch` example and added new subsection [8.3 Pushing new local branch](https://anyone-can-cook.github.io/rclass2/lectures/git_and_github/git_and_github.html#83_Pushing_new_local_branch)

**Comment by ozanj** [comment]
Thx!

 

Ozan Jaquette

Associate Professor

he/him/his

Higher Education and Organizational Change

UCLA Graduate School of Education & Information Studies

Moore Hall 3038

 <mailto:ozanj@ucla.edu> ozanj@ucla.edu

310-206-3030

 

 <https://emraresearch.org/> https://emraresearch.org/ 

 

“Don’t tell me what you value. Show me your budget and I’ll tell you what you value.” – Joe Biden
