### ISSUE TITLE
git lecture edit

### ISSUE THREAD

**Issue by mpatricia01** [anyone-can-cook/rclass2#9]
Changes to git lecture:

1. Under the git log section, add a git log - n option to the lecture slides.  
2. Add instructions on changing branch name to `main`.
3. Change all references to `master` branch to `main` branch in lecture materials/problem sets

@cyouh95 , @ozanj , @mpatricia01

**Comment by cyouh95** [comment]
These should be updated now. Only thing is the images used in the lecture still contain `master`.

**Comment by ozanj** [comment]
how much work is it for images to be changed from `master` to `main`?

@mpatricia01 - do you think it is important for `master` to be scrubbed from all aspects of the git unit?

**Comment by mpatricia01** [comment]
It might be harder to change images from `master` to `main` because most images we get off the web. We would have to scour the internet to find images we can replace them with. Or an alternative would be to save the images on github and edit them manually, if we can? 

I think it is important we remove any mention of `master`. As mentioned above, it might be difficult because a lot of resources online still use that name. So I think we could work towards that goal in the coming weeks and/or months.

**Comment by ozanj** [comment]
sounds good @mpatricia01 !

I am closing this issue.

Patricia - if you want you can create an issue about changing master to main and we will leave it open until we finish doing so
